### ISSUE TITLE
Elastic5 date by feilds

### ISSUE THREAD

**Issue by panda87** [Landoop/stream-reactor#265]
It's common to index docs according the ingest time of event and not according Kafka time when it indexed the event. This gives the developer good way to manage the events time which es index (by time) this will be indexed to in case of downtime before it ingested into kafka.

So if we can take a time field (configurable like iso8601) and parse its date and according the choose the appropriate es index to be ingested, this can be very helpful

Thanks
D.

**Comment by andrewstevenson** [comment]
@panda87 So you want a configurable target based on field in the kafka payload?

**Comment by panda87** [comment]
Exactly!
So the first event time (before indexed in kafka) will be the "truth" time instead further processing.
Think that you are using kafka-streams to enrich event and send it back to new topic, the event in the new topic will get new metadata date, and you will loose the "upstream" date. So if you always can track on specific date, this will be very helpful

**Comment by caiooliveiraeti** [comment]
Hello @andrewstevenson and @panda87. In issue #266 I will add pipeline ingest support. So for adds date in index name you can use: https://www.elastic.co/guide/en/elasticsearch/reference/current/date-index-name-processor.html

**Comment by andrewstevenson** [comment]
closed with #266
