### ISSUE TITLE
Elastic5 pipeline definitions 

### ISSUE THREAD

**Issue by panda87** [Landoop/stream-reactor#266]
One of the greatest features es released in v5.x is the ability to manipulate logs before they been indexed. The pipeline has grok, drop, rename processors that easily replace logstash in many areas.

Adding pipeline id with bulk API to the configuration will help to enrich the logs parse them correctly

Thanks
D.

**Comment by Antwnis** [comment]
Hi @panda87 this functionality has now been added to both ES5 and ES6 connectors

The KCQL DSL now allows 
```
SELECT * FROM topicA INTO indexA WITHPIPELINE  "p1"
```

New release will become available this week - on the meanwhile you'll have to build from source
