### ISSUE TITLE
Cassandra Source: make time slice configurable

### ISSUE THREAD

**Issue by CodeSmell** [Landoop/stream-reactor#278]
Work on `CassandraTableReader` in the Cassandra Source so that the time slice of data that is used to pull data from a Cassandra table can be limited to a smaller and configurable range. 

Currently the CQL to pull data from a table uses a time slice that is based on getting all of the rows since the last successful time up to and including the current time. However, since we can't limit the rows retrieved using the LIMIT CQL statement, often the query can pull back too many rows that result in performance problems. 

Specifically, if we are inserting a million rows every minute or two and it takes an hour to pull that data and publish to Kafka then the next pull results in an even larger data set. This problem compounds over time. 

Willing to submit PR

**Comment by CodeSmell** [comment]
One challenge is to decide how to set a "default" starting time since January 1, 1900 will cause a large delay as the task works forward in small increments of say 10 seconds. 

Should this be configurable as well?

**Comment by Antwnis** [comment]
Is it possibly to have an <initialization> phase to query for the minimum <ts> and then move into the ticking phase - to increment by the (configurable) 60 sec ?

**Comment by CodeSmell** [comment]
I think we are going to need something like that
Here is quick idea...
```    
    val previous = dateFormatter.parse(cqlGenerator.getDefaultOffsetValue(tableOffset).get)
    
    // set the upper bound
    val now = new Date()
    val nextTimeSlice = if (previous.getYear == 0) {
      // we can't do small time slices if default is Jan 1, 1900
      // so for now advance to current date time
      now
    } else {
      // we want to process in small time slices but never in the future
      // TODO: probably need new config setting for time slice but for now using 10 seconds
      val upperBound = previous.getTime + 10000
      val upperDate = new Date(upperBound)
      if (now.getTime < upperBound) now else new Date(upperBound)
    }
```

One other issue is previous is currently based on the timestamp of the last row processed
If that was at time = 2017-09-15 20:26:14.515Z (previous)
And if the next inserted row was at 2017-09-15 20:26:34.515Z
We would end up with an upper bound of 2017-09-15 20:26:24.515Z
Then we would get stuck because previous would never advance...

might need to have previous set to the upperbound
thoughts?

**Comment by CodeSmell** [comment]
As noted in comment above we have the challenge that we could get stuck in the given scenario:
Last row timestamp = 2017-09-15 20:26:14.515Z 
Next inserted row timestamp = 2017-09-15 20:26:34.515Z

Instead of changing what value `previous` is storing/holding, we could do buildup of duration, like this

```
if (rowsProcessed == 0) {
   // keep adding polling interval to duration when we don't get any hits
   timeSliceValue += config.timeSliceDuration + config.pollingInterval
} else {
   // set value back to config
   timeSliceValue = config.timeSliceDuration
}
```

Note: `config.timeSliceDuration` would be the config value for how much of a time slice we should process (10 seconds or whatever) 

That means that the code to calculate could look like this:
```
    val previous = dateFormatter.parse(cqlGenerator.getDefaultOffsetValue(tableOffset).get)
    
    // set the upper bound
    val now = new Date()
    val nextTimeSlice = if (previous.getYear == 0) {
      // we can't do small time slices if default is Jan 1, 1900
      // so for now advance to current date time
      now
    } else {
      // we want to process in small time slices but never in the future
      val upperBound = previous.getTime + timeSliceValue
      val upperDate = new Date(upperBound)
      if (now.getTime < upperBound) now else new Date(upperBound)
    }
```

**Comment by Antwnis** [comment]
I have a small point regarding monitoring. 

If you have a record at 14 sec 515 msec
and next record is    at 34 sec 515 msec
and the tick every 10 seconds

I would still go with an empty tick 14-24 rather than increase temporarily the tick to 20 seconds

Then you could have an operational alert - i.e. if NO data for 3 ticks - send alerts
If we buildup the duration, it would become much harder to build more meaningful alerting

**Comment by CodeSmell** [comment]
We can go that route, but if we don't just to be sure...

Given
```
duration = 10 seconds
polling = 30 seconds
```
without any temp increase we get
```
row inserted at 14 sec 
KC runs at 15 sec 
--- publishes data to Kafka
--- sets the offset = 14 sec 
KC runs at 45 sec w/ where clause range of 14 sec - 24 sec 
--- no rows so leave offset = 14 sec
row inserted at 34 sec
KC runs at 55 sec w/ where clause range of 14 sec - 24 sec
--- no rows so leave offset = 14 sec
KC runs at 05 sec w/ where clause range of 14 sec - 24 sec
--- no rows so leave offset = 14 sec
...
```
Once there is a lack of inserts into Cassandra within a time period that is >= time slice duration the connector would get stuck. This may not due to a problem in either the application inserting into Cassandra or the KC connector, but the way that data is coming in and being processed. Once it happens, it can't fix itself no much how much data is inserted into Cassandra. 

With the temp increment we get
```
row inserted at 14 sec 
KC runs at 15 sec 
--- publishes data to Kafka
--- sets the offset = 14 sec 
KC runs at 45 sec w/ where clause range of 14 sec - 24 sec 
--- no rows (so augment time slice to duration + polling) = 40 sec
row inserted at 34 sec
KC runs at 55 sec w/ where clause range of 14 sec - 54 sec
--- publishes data to Kafka
--- sets the offset = 34 sec 
--- resets time slice = duration = 10 sec
KC runs at 05 sec w/ where clause range of 34 sec - 44 sec
...
```
Of course, just using that example, that has a problem in that it can create an overlap in the processing of some data... so maybe there is another way to handle these cases

**Comment by CodeSmell** [comment]
Was thinking that if duration was longer than polling that might fix it, but even that doesn't get us there...
```
duration = 20 seconds
polling = 10 seconds
```
we get
```
row inserted at 14 sec 
KC runs at 15 sec 
--- publishes data to Kafka
--- sets the offset = 14 sec 
KC runs at 25 sec w/ where clause range of 14 sec - 25 sec (can't go into future) 
--- no rows (so augment time slice to duration + polling) = 30 sec
row inserted at 34 sec
KC runs at 35 sec w/ where clause range of 14 sec - 35 sec  (can't go into future) 
--- publishes data to Kafka
--- sets the offset = 34 sec 
--- resets time slice = duration = 10 sec
KC runs at 45 sec w/ where clause range of 34 sec - 44 sec
...
```

**Comment by Antwnis** [comment]
@CodeSmell how is this working for you now ? Can the ticket be resolved/closed ?

**Comment by CodeSmell** [comment]
@Antwnis 
We are conducting some load tests this week w/ the snapshot build

I think there are two open areas, in addition to that test
1) updating config so that the time slice can be easily changed (maybe that should be another issue)
2) is there a better way to advance from Jan. 1, 1900 then using the current date/time

**Comment by Antwnis** [comment]
So on point 2 @CodeSmell on the FTP connector - i.e. search for `PT1M` on  
http://www.landoop.com/blog/2017/02/ftp-to-kafka/ - we use the https://en.wikipedia.org/wiki/ISO_8601 standard to define time

So from the wiki - P1M would mean start from 1 month ago ..
other-wise maybe a config could explicitly set it to start at YYYYMMDD-HH-mm
or another option would be the connector to figure out when to auto-start at 

quite a few choices, question is which one fits bets your use-case

**Comment by CodeSmell** [comment]
Sounds cool, @Antwnis 
I'll take a look at these options

**Comment by CodeSmell** [comment]
Bit sidetracked this week. We had to roll out an unplanned release and I had to give up my QA environment for testing. I had hoped to use that for load testing these changes. Will keep you posted.

Unless there are objections, I am leaning towards adding another config option that accepts the ISO-8601 durations. If provided it would override the default of Jan 1, 1900 with the calculated date/time.

**Comment by CodeSmell** [comment]
The time slice handling seems to be running well so the feature works as intended. However, initial tests did not show the performance improvements that we hoped for, debugging uncovered this problem #300 
I think this can be closed with the addition of the following issues: 
- #301
- #302
