### ISSUE TITLE
 jms-src connector does not remove messages from queue 

### ISSUE THREAD

**Issue by AlexanderScherbatiy** [Landoop/stream-reactor#310]
### What version of the Stream Rector are you reporting this issue for?
 stream-reactor-0.3.0-3.3.0.tar.gz

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
confluent-oss-3.3.0-2.11.tar.gz

### Have you consulted our [FAQs](http://docs.datamountaineer.com/en/latest/faq.html) page first?
Yes, this one: http://docs.datamountaineer.com/en/latest/faq.html
### Have you read the [docs](http://docs.datamountaineer.com/)?
Yes, this one:  http://docs.datamountaineer.com/en/latest/jms-source.html
### What is the expected behaviour?
Messages are removed from Active MQ when they are transferred to Kafka topic 
### What was observed?
Messages are not removed from Active MQ when they are transferred to Kafka topic.

I looked at the test src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSSourceTaskTest.scala and it checks that the messages are removed from the Queue:

---
    messages.foreach(m => {
      queueProducer.send(m)
      m.acknowledge()
    })

    eventually {
      val records = task.poll().asScala
      records.size shouldBe 10
      records.head.valueSchema().toString shouldBe JMSStructMessage.getSchema().toString
    }

    messagesLeftToAckShouldBe(10)

    task.poll()
    task.commit()

    messagesLeftToAckShouldBe(0)
---

So it is not clear for me why they are not removed in my case.
Property files and producer/consumer sources are provided below.

### What is your Connect cluster configuration (connect-avro-distributed.properties)?

bootstrap.servers=localhost:9092
group.id=connect-cluster
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081
config.storage.topic=connect-configs
offset.storage.topic=connect-offsets
status.storage.topic=connect-statuses
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
plugin.path=/home/test/tools//stream-reactor-0.3.0-3.3.0

### What is your connector properties configuration (my-connector.properties)?
name=jms-source
connector.class=com.datamountaineer.streamreactor.connect.jms.source.JMSSourceConnector
tasks.max=1
connect.jms.url=tcp://localhost:61616
connect.jms.connection.factory=ConnectionFactory
connect.jms.initial.context.factory=org.apache.activemq.jndi.ActiveMQInitialContextFactory
connect.jms.queues=queue-source
connect.jms.kcql=INSERT INTO topic-jms-source SELECT * FROM queue-source AUTOEVOLVE WITHTYPE QUEUE
### Please provide full log files (redact and sensitive information)

JMS Producer:
------------
        ConnectionFactory factory = new ActiveMQConnectionFactory(getJMSServer());
        try (Connection connection = factory.createConnection();) {
            Session session = connection.createSession(false, Session.CLIENT_ACKNOWLEDGE);
            Queue queue = session.createQueue(queueName);
            MessageProducer producer = session.createProducer(queue);

            for (File xmlFile : xmlFiles) {
                String message = fileToString(xmlFile);
                Message msg = session.createTextMessage(message);
                producer.send(msg);
                msg.acknowledge();
            }
        }
------------

Kafka Consumer:
------------
        Properties props = new Properties();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, projectProperties.getKafkaBroker());
        props.put(ConsumerConfig.GROUP_ID_CONFIG, ProjectUtils.KAFKA_GROUP_ID_XML);

        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, KafkaAvroDeserializer.class.getName());
        props.put(KafkaAvroSerializerConfig.SCHEMA_REGISTRY_URL_CONFIG, projectProperties.getSchemaRegistryUrlConfig());

        try (KafkaConsumer<String, GenericRecord> consumer = new KafkaConsumer<>(props)) {

            String topicName = projectProperties.getKafkaTopicJMSSourceXML();
            consumer.subscribe(Arrays.asList(topicName));

            while (true) {
                ConsumerRecords<String, GenericRecord> records = consumer.poll(100);
                if (!records.isEmpty()) {
                    for (ConsumerRecord<String, GenericRecord> record : records) {

                        GenericRecord recordValue = record.value();
                        String message = SerdeUtils.extractPayload(recordValue);
                        System.out.printf("offset: %s, message: '%s'%n", record.offset(), message);
                    }
                }
            }
        }
------------

**Comment by andrewstevenson** [comment]
@AlexanderScherbatiy this has been fixed in #291 . If you build from master you'll get the fic

**Comment by AlexanderScherbatiy** [comment]
Do you have a release with the fix?

**Comment by AlexanderScherbatiy** [comment]
If I build the JMS Source connector from sources will I be able to use it with Confluent 3.3?
If so, what should I do?
- confluent unload jms-source
- confluent stop
- remove jms connector jar from stream-reactor/libs
- add there new compiled jar
- start confluent and load jms-src
Is it enough?

**Comment by andrewstevenson** [comment]
@AlexanderScherbatiy It will be in the next release. All you need to do it replace the jar and restart your connect workers.

**Comment by AlexanderScherbatiy** [comment]
Do you have any estimation when the next release is planning?

**Comment by andrewstevenson** [comment]
We are busy releasing https://www.landoop.com/ so I won't be for a few weeks.

**Comment by Antwnis** [comment]
The release has been completed on `Lenses` -> https://landoop.com/docs/lenses/ 👍 

I am re-opening this issue so that we can close it once we release `stream-reactor`
