### ISSUE TITLE
Cassandra Incremental Source Connector behaves as Bulk.

### ISSUE THREAD

**Issue by nehabhardwaj01** [Landoop/stream-reactor#311]
**Stream Rector Version:** stream-reactor-0.2.4-3.1.1

**Confluent:** confluent-3.2.0

**Cassandra Version:** apache-cassandra-3.9

**connect-avro-distributed.properties:**
bootstrap.servers=localhost:9092
group.id=connect-cluster
key.converter.schemas.enable=true
value.converter.schemas.enable=true
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.topic=connect-offsets
config.storage.topic=connect-configs
status.storage.topic=connect-status
offset.flush.interval.ms=10000

**Connector Properties:** 

`timeuuid-connector`

connector.class=com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceConnector
connect.cassandra.import.mode=incremental
connect.cassandra.key.space=test
connect.cassandra.contact.points=localhost
topics=test-timeuuid-topic
connect.cassandra.source.timestamp.type=timeuuid
name=timeuuid-connector
connect.cassandra.assigned.tables=orders
connect.cassandra.source.kcql=INSERT INTO test-timeuuid-topic SELECT * FROM orders PK created

`timeuuid-connector-v1`

connector.class=com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceConnector
connect.cassandra.import.mode=incremental
connect.cassandra.key.space=test
connect.cassandra.contact.points=localhost
topics=test-timeuuid-topic-v1
connect.cassandra.source.timestamp.type=timeuuid
name=timeuuid-connector-v1
connect.cassandra.assigned.tables=orders
connect.cassandra.source.kcql=INSERT INTO test-timeuuid-topic-v1 SELECT * FROM orders PK created

**Expected behavior:** The Source Connector should work in the incremental mode for the given configuration. 

**Actual Output:** The connector works as expected(INCREMENTAL) until some other connector is created(posted).
As soon as some new connector is created, all the existing connectors gets refreshed and dump all the existing data from their respective source to the subscribed topics(same as BULK).

**Scenario:**

Create Table `orders`:
create table orders (id int, created timeuuid, product text, qty int, price float, PRIMARY KEY (id, created))
WITH CLUSTERING ORDER BY (created asc);

INSERT INTO orders (id, created, product, qty, price) VALUES (1, now(), 'OP-DAX-P-20150201-95.7', 100, 94.2);
INSERT INTO orders (id, created, product, qty, price) VALUES (2, now(), 'OP-DAX-C-20150201-100', 100, 99.5);
INSERT INTO orders (id, created, product, qty, price) VALUES (3, now(), 'FU-KOSPI-C-20150201-100', 200, 150);

Topic data after creating `timeuuid-connector`: ./bin/kafka-avro-console-consumer --new-consumer --bootstrap-server localhost:9092 --topic test-timeuuid-topic --from-beginning
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/neha/application/confluent-3.2.0/share/java/kafka-serde-tools/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/neha/application/confluent-3.2.0/share/java/schema-registry/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
{"id":{"int":1},"created":{"string":"1c47bd90-bed3-11e7-8493-17c792b36d2a"},"price":{"float":94.2},"product":{"string":"OP-DAX-P-20150201-95.7"},"qty":{"int":100}}
{"id":{"int":3},"created":{"string":"1d4de2f0-bed3-11e7-8493-17c792b36d2a"},"price":{"float":150.0},"product":{"string":"FU-KOSPI-C-20150201-100"},"qty":{"int":200}}
{"id":{"int":2},"created":{"string":"1c49e070-bed3-11e7-8493-17c792b36d2a"},"price":{"float":99.5},"product":{"string":"OP-DAX-C-20150201-100"},"qty":{"int":100}}

Topic data after some new connector is created(say `timeuuid-connector-v1` with the properties specified above):
./bin/kafka-avro-console-consumer --new-consumer --bootstrap-server localhost:9092 --topic test-timeuuid-topic --from-beginning
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/neha/application/confluent-3.2.0/share/java/kafka-serde-tools/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/neha/application/confluent-3.2.0/share/java/schema-registry/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
{"id":{"int":1},"created":{"string":"1c47bd90-bed3-11e7-8493-17c792b36d2a"},"price":{"float":94.2},"product":{"string":"OP-DAX-P-20150201-95.7"},"qty":{"int":100}}
{"id":{"int":3},"created":{"string":"1d4de2f0-bed3-11e7-8493-17c792b36d2a"},"price":{"float":150.0},"product":{"string":"FU-KOSPI-C-20150201-100"},"qty":{"int":200}}
{"id":{"int":2},"created":{"string":"1c49e070-bed3-11e7-8493-17c792b36d2a"},"price":{"float":99.5},"product":{"string":"OP-DAX-C-20150201-100"},"qty":{"int":100}}
{"id":{"int":1},"created":{"string":"1c47bd90-bed3-11e7-8493-17c792b36d2a"},"price":{"float":94.2},"product":{"string":"OP-DAX-P-20150201-95.7"},"qty":{"int":100}}
{"id":{"int":3},"created":{"string":"1d4de2f0-bed3-11e7-8493-17c792b36d2a"},"price":{"float":150.0},"product":{"string":"FU-KOSPI-C-20150201-100"},"qty":{"int":200}}
{"id":{"int":2},"created":{"string":"1c49e070-bed3-11e7-8493-17c792b36d2a"},"price":{"float":99.5},"product":{"string":"OP-DAX-C-20150201-100"},"qty":{"int":100}}
{"id":{"int":2},"created":{"string":"1c49e070-bed3-11e7-8493-17c792b36d2a"},"price":{"float":99.5},"product":{"string":"OP-DAX-C-20150201-100"},"qty":{"int":100}}
{"id":{"int":1},"created":{"string":"1c47bd90-bed3-11e7-8493-17c792b36d2a"},"price":{"float":94.2},"product":{"string":"OP-DAX-P-20150201-95.7"},"qty":{"int":100}}
{"id":{"int":3},"created":{"string":"1d4de2f0-bed3-11e7-8493-17c792b36d2a"},"price":{"float":150.0},"product":{"string":"FU-KOSPI-C-20150201-100"},"qty":{"int":200}}

The topic automatically gets the undesired complete set of data into the topic.

**Comment by andrewstevenson** [comment]
@nehabhardwaj01 If you are posting a new connector, i.e. with a different name? Is so then there is no stored offset to recover. This offset is used to form the upper and lower bounds. If no offset is found the connector will pull in all existing data and start incrementally pulling in new data.

Connectors are independent and don't know about each other.

**Comment by nehabhardwaj01** [comment]
Yes, I am posting a new connector but the creation of this new connector is affecting the existing connectors, and their topics as well.

Every time I create a new connector, the existing running connectors also gets refreshed with the complete data set from their respective sources.

**Comment by andrewstevenson** [comment]
so topic test-timeuuid-topic gets reload? Adding a new connector causes a rebalance amongst existing connectors but it shouldn't be reloading all the data. 

I see you have the ``--from-beginning`` on the console consumer,  this will cause the consumer to read from the beginning everytime, so you see the originals. Can you run without this flag on the first connectors topic and post in a new connector?

**Comment by nehabhardwaj01** [comment]
I guess that is not an issue. We can see the message count continuously increasing in our topic queue. Even if we drop --from beginning, the problem still prevails.

**Comment by andrewstevenson** [comment]
Are new records being added to cassandra? Can you provide the logs including before you add a new connector? Also check the connect-offset topic to check if the offsets are being committed.

**Comment by nehabhardwaj01** [comment]
cqlsh:test> select * from orders;

 id | created                              | price | product                 | qty
----+--------------------------------------+-------+-------------------------+-----
  1 | 1c47bd90-bed3-11e7-8493-17c792b36d2a |  94.2 |  OP-DAX-P-20150201-95.7 | 100
  2 | 1c49e070-bed3-11e7-8493-17c792b36d2a |  99.5 |   OP-DAX-C-20150201-100 | 100
  3 | 1d4de2f0-bed3-11e7-8493-17c792b36d2a |   150 | FU-KOSPI-C-20150201-100 | 200


This is the initial dataset of the table, and no new rows are being added before/after creating connectors.
1) Create timeuuid-connector
connector logs for the first connector: `timeuuid_connector.log`
Let this connector run, and check
[timeuuid_connector.log](https://github.com/datamountaineer/stream-reactor/files/1436685/timeuuid_connector.log)
[timeuuid_connector_v1.log](https://github.com/datamountaineer/stream-reactor/files/1436686/timeuuid_connector_v1.log)
[timeuuid_connector.log](https://github.com/datamountaineer/stream-reactor/files/1436689/timeuuid_connector.log)


 its topic data(i.e, test-timeuuid-topic), also let the consumer run, to continuously keep track of data

2) Create a new connector(i.e, timeuuid-connector-v1)
Connector logs after a new connector is created: `timeuuid_connector_v1.log`

Please notice the following statements in `timeuuid_connector_v1.log` 
[2017-11-02 11:28:16,193] INFO Processed 3 rows for table test-timeuuid-topic.orders
[2017-11-02 11:28:16,206] INFO Processed 3 rows for table test-timeuuid-topic-v1.orders

However, test-timeuuid-topic already has its data, but after a new connector is created, 3 rows are again processed for this topic.

**Comment by andrewstevenson** [comment]
@nehabhardwaj01 Can you try with the latest release? The clients are backwards compatible with kafka 10.

**Comment by nehabhardwaj01** [comment]
For release 0.2.6 the bug persists.
But, as per my understanding, there's no such issue in release 0.3.

**Comment by andrewstevenson** [comment]
Please try 0.3.0. We recommended upgrading. The clients are compatible and you get classloader isolation with Kafka 0.11

**Comment by andrewstevenson** [comment]
@nehabhardwaj01 Did upgrading resolve your issue?

**Comment by nehabhardwaj01** [comment]
Yes, Confluent 3.0 Worked for me.

**Comment by andrewstevenson** [comment]
@nehabhardwaj01 thanks!
