### ISSUE TITLE
Kafka Connect Influx 

### ISSUE THREAD

**Issue by andymason57** [Landoop/stream-reactor#315]
The installation instructions for the Kafka Connect Influx sink are not compatible with the latest version of influxDB (v1.3). 
From the InfluxDB website (https://docs.influxdata.com/influxdb/v1.3/tools/web_admin/) : 

'In version 1.3, the web admin interface is no longer available in InfluxDB. The interface does not run on port 8083 and InfluxDB ignores the [admin] section in the configuration file if that section is present. '

**Comment by Antwnis** [comment]
Thanks @andymason57 for the feedback. We will be making a new release soon, and as part of that we'll run the full integration tests & update the docs accordingly

**Comment by andrewstevenson** [comment]
@andymason57 we also accept PRs! Contributions always welcome!

https://github.com/datamountaineer/docs

**Comment by andrewstevenson** [comment]
Docs updated.
