### ISSUE TITLE
MqttSourceConnector - ERROR (32103):Unable to Connect to Server (if 'allow_anonymous' is set to 'False' in mosquitto.conf)

### ISSUE THREAD

**Issue by vossilius** [Landoop/stream-reactor#316]
The MqttSourceConnector fails to connect to the broker during authentication which can be circumvented by setting ```allow_anonymous  true``` in _mosquitto.conf_.
Find more details at [#34](https://github.com/datamountaineer/docs/issues/34#issuecomment-343472093).

---
**Test Environment:**
- Docker image: landoop/fast-data-dev:cp3.3.0
- Confluent OSS v3.3.0 - Kafka v0.11.0.0 (1× Broker, 1× Schema Registry, 1× Connect Distributed Worker, 1× REST Proxy, 1× Zookeeper)
- Landoop Schema Registry UI v0.9.1
- Landoop Kafka Topics UI v0.9.3
- Landoop Kafka Connect UI v0.9.2
- MQTT server (mosquitto) in LAN

**Comment by caiooliveiraeti** [comment]
Hello @vossilius this is a same problem related in this issue #374. I sended the pull request #376 for resolve this problem.

**Comment by Antwnis** [comment]
Hi @vossilius - This has been addressed via #376 that has been merged to master.
If you build the connector you should be good to go !
