### ISSUE TITLE
issue/complexities with influxDB Connector

### ISSUE THREAD

**Issue by sachinkademane** [Landoop/stream-reactor#320]
Hi.. i m using stream reactor 3.3 n confluent 0.3... and i get input to kafka in json arrays which needs to be put into influxdb...
ex : my data is in form of [{ }, { }, { }] this type of data will be coming every second and i need to put the elements into the influxdb....

But as per my knowledge KCQL queries doesnt have support for Json arrays [{},{},{}] that should be converted to Json elements or Json objects  {} {} {} and put in influx.... can u try to include thator is there any other way for doing this?

**Comment by sachinkademane** [comment]
@andrewstevenson 
 can u give me a solution for this?

**Comment by stheppi** [comment]
@sachinkademane 
 we already told you on the item raised on the documentation that this functionality is not supported.
 We gladly accept contribution so please provide a pull request.

 Alternatively you can do a work around and send each item in your json array on its own - if you have control over the producer i would suggest you do that. the kafka producer does batching anyway.
