### ISSUE TITLE
InlfuxDB Sink issues 

### ISSUE THREAD

**Issue by vivekatme** [Landoop/stream-reactor#329]
Error : 

> you can't select all the fields because 'fields' is resolving to a type: 'java.util.hashmap' which is not supported by influxdb api

I followed http://www.landoop.com/blog/2016/12/kafka-influxdb/ for setting up the kafka-influx sink. 

The difference I have is that I am receiving the metrics from Telegraf , i.e the stack is 

Telegraf->Kafka->Kafka-Influx-Sink->InluxDB. 

Telegraf is producing the metrics in JSON  and received in Kafka topic as follows

`Key Viveks-MacBook-Pro.local
Value {"fields":{"free":473169920,"total":3221225472,"used":2748055552,"used_percent":85.31087239583334},"name":"swap","tags":{"dc":"us-east-1","host":"Viveks-MacBook-Pro.local","rack":"1a"},"timestamp":1511521090}`

Sink is correctly configured with following values 

`"connector.class": "com.datamountaineer.streamreactor.connect.influx.InfluxSinkConnector",
  "connect.influx.url": "http://172.17.0.2:8086",
  "connect.influx.db": "cymatics",
  "topics": "fleet",
  "tasks.max": "1",
  "connect.influx.kcql": "INSERT INTO influxMeasure SELECT * FROM fleet WITHTIMESTAMP sys_time()",
  "name": "InfluxSinkConnector",
  "connect.influx.username": "-",
  "connect.influx.password": "-"`

Following is the connector configuraiton
`key.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schema.registry.url=http://localhost:8081
value.converter.schemas.enable=false`

Landoop service version  is as follows

<img width="403" alt="screen shot 2017-11-24 at 4 33 27 pm" src="https://user-images.githubusercontent.com/17191080/33207936-a0b73e88-d135-11e7-8c8b-ac3de9b286b8.png">

**Comment by stheppi** [comment]
@vivekatme 
  This It is actually a validation. The sink correctly says the incoming data and the KCQL are not in line with the rules.
  InfluxDb point builder API allows only primitive types. Here is the code from the InfluxDb Client API
``` public Builder field(final String field, Object value) {
      if (value instanceof Number) {
        if (value instanceof Byte) {
          value = ((Byte) value).doubleValue();
        } else if (value instanceof Short) {
          value = ((Short) value).doubleValue();
        } else if (value instanceof Integer) {
          value = ((Integer) value).doubleValue();
        } else if (value instanceof Long) {
          value = ((Long) value).doubleValue();
        } else if (value instanceof BigInteger) {
          value = ((BigInteger) value).doubleValue();
        }
      }
      fields.put(field, value);
      return this;
    }
```
Your incoming json is nested:
```{
	"fields": {
		"free": 473169920,
		"total": 3221225472,
		"used": 2748055552,
		"used_percent": 85.31087239583334
	},
	"name": "swap",
	"tags": {
		"dc": "us-east-1",
		"host": "Viveks-MacBook-Pro.local",
		"rack": "1a"
	},
	"timestamp": 1511521090
}```

Select `*` means inserting the nested `fields` which can't happen.
What you want is a KCQL like this:

```INSERT INTO influxMeasure 
   SELECT fields.free, fields.total, fields.used, fields.used_percent FROM fleet WITHTIMESTAMP sys_time()  WITHTAG ( tags.dc, tags.host, tags.rack)```
```

**Comment by vivekatme** [comment]
Thanks @stheppi  for your help , this will mean schema for each topic is kind of fixed and I can only have certain property names that can be selected from the fields.    In my case Telegraf is sending host level metrics https://github.com/influxdata/telegraf/tree/master/plugins/inputs/system to a single topic for example  : SWAP information comes as 

`"fields": {
		"free": 473169920,
		"total": 3221225472,
		"used": 2748055552,
		"used_percent": 85.31087239583334
	},
	"name": "swap",
	"tags": {
		"dc": "us-east-1",
		"host": "Viveks-MacBook-Pro.local",
		"rack": "1a"
	},
	"timestamp": 1511521090
}`
and 
CPU information comes as 

`{
  "fields": {
    "usage_guest": 0,
    "usage_guest_nice": 0,
    "usage_idle": 75.3,
    "usage_iowait": 0,
    "usage_irq": 0,
    "usage_nice": 0,
    "usage_softirq": 0,
    "usage_steal": 0,
    "usage_system": 10.1,
    "usage_user": 14.6
  },
  "name": "cpu",
  "tags": {
    "cpu": "cpu0",
    "dc": "us-east-1",
    "host": "Viveks-MacBook-Pro.local",
    "rack": "1a"
  },
  "timestamp": 1511764060
}`

I want to both (and) more information to be relayed to influxDB fluidly. 

Is this supported by this connector ?
