### ISSUE TITLE
InlfuxDB Sink Feature check

### ISSUE THREAD

**Issue by vivekatme** [Landoop/stream-reactor#338]
This is in continuity to https://github.com/Landoop/stream-reactor/issues/329 

Thanks @stheppi for your help , this will mean schema for each topic is kind of fixed and I can only have certain property names that can be selected from the fields. In my case Telegraf is sending host level metrics https://github.com/influxdata/telegraf/tree/master/plugins/inputs/system to a single topic for example : SWAP information comes as

"fields": { "free": 473169920, "total": 3221225472, "used": 2748055552, "used_percent": 85.31087239583334 }, "name": "swap", "tags": { "dc": "us-east-1", "host": "Viveks-MacBook-Pro.local", "rack": "1a" }, "timestamp": 1511521090 }
and
CPU information comes as

{ "fields": { "usage_guest": 0, "usage_guest_nice": 0, "usage_idle": 75.3, "usage_iowait": 0, "usage_irq": 0, "usage_nice": 0, "usage_softirq": 0, "usage_steal": 0, "usage_system": 10.1, "usage_user": 14.6 }, "name": "cpu", "tags": { "cpu": "cpu0", "dc": "us-east-1", "host": "Viveks-MacBook-Pro.local", "rack": "1a" }, "timestamp": 1511764060 }

I want to both (and) more information to be relayed to influxDB fluidly.

Is this supported by this connector ?

**Comment by stheppi** [comment]
@vivekatme 
Let's take the CPUs
 ```json
{
	"fields": {
		"usage_guest": 0,
		"usage_guest_nice": 0,
		"usage_idle": 75.3,
		"usage_iowait": 0,
		"usage_irq": 0,
		"usage_nice": 0,
		"usage_softirq": 0,
		"usage_steal": 0,
		"usage_system": 10.1,
		"usage_user": 14.6
	},
	"name": "cpu",
	"tags": {
		"cpu": "cpu0",
		"dc": "us-east-1",
		"host": "Viveks-MacBook-Pro.local",
		"rack": "1a"
	},
	"timestamp": 1511764060
}
```

you should use the following KSQL syntax:

```sql
INSERT INTO cpu 
SELECT fields.*
FROM $YOUR_TOPIC_WITH_CPU_DATA
WITHTIMESTAMP timestamp
TIMESTAMPUNIT=MILLISECONDS
WITHTAG (tags.cpu, tags.dc, tags.host, tags.rack)

```

I assume the timestamp from Telegraf is in millis acuracy. 
You need to take the latest from master and build it locally.

Let us know how it goes.

**Comment by andrewstevenson** [comment]
@vivekatme Closing, reopen if you still have an issue.
