### ISSUE TITLE
Redis sink connector doesn't prefix key

### ISSUE THREAD

**Issue by vlad1777d** [Landoop/stream-reactor#350]
### What version of the Stream Rector are you reporting this issue for?

I use only kafka-connect-redis-0.3.0-3.3.0-all.jar

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?

No, I use Confluent 4.0.0.

### Have you consulted our [FAQs](http://docs.datamountaineer.com/en/latest/faq.html) page first?

Yes

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?

No, I have only Redis connector

### Have you read the [docs](http://docs.datamountaineer.com/)?

Yes

### What is the expected behaviour?

here: http://docs.datamountaineer.com/en/latest/redis.html
is written:
>We can prefix the name of the Key using the INSERT statement:
INSERT INTO FX- SELECT price from yahoo-fx PK symbol

### What was observed?

I have such connector:
> {
  "connector.class": "com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector",
  "connect.redis.port": "6379",
  "connect.redis.kcql": "INSERT INTO MONGO2- SELECT after as after2, source, ts_ms as ts_ms2 FROM test-mongodb-source.test.TestRecord2 PK source",
  "tasks.max": "1",
  "topics": "test-mongodb-source.test.TestRecord2",
  "connect.redis.host": "redis",
  "name": "test-redis-sink-12"
}

And it created such keys:
> keys *
1) "MONGO2-"

Value:
> mget MONGO2-
1) "{\"after2\":null,\"source\":{\"name\":\"test-mongodb-source\",\"rs\":\"testrp\",\"ns\":\"test.TestRecord2\",\"sec\":1514998711,\"ord\":1,\"h\":4424241304727296797,\"initsync\":null},\"ts_ms2\":1514998711760}"

So it doesn't made key prefixed with "MONGO-", but wrote only "MONGO-"

### What is your Connect cluster configuration (connect-avro-distributed.properties)?

I don't use AVRO, I use JSON.

### What is your connector properties configuration (my-connector.properties)?

> {
  "connector.class": "com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector",
  "connect.redis.port": "6379",
  "connect.redis.kcql": "INSERT INTO MONGO2- SELECT after as after2, source, ts_ms as ts_ms2 FROM test-mongodb-source.test.TestRecord2 PK source",
  "tasks.max": "1",
  "topics": "test-mongodb-source.test.TestRecord2",
  "connect.redis.host": "redis",
  "name": "test-redis-sink-12"
}

### Please provide full log files (redact and sensitive information)

I didn't saw any sensitive information in this connector's logs.

**Comment by andrewstevenson** [comment]
@vlad1777d The docs are a bit confusing but the prefix is only for multiple sorted sets, for this you need to add the ``STOREAS SortedSet(score=timestamp)``

http://docs.datamountaineer.com/en/latest/redis.html#multiple-sorted-sets

**Comment by vlad1777d** [comment]
@andrewstevenson , thank you.

But is there any way to set a key for Redis from value taken from topic with KSQL ?
I mean in case, when I need value to be a string.

**Comment by stheppi** [comment]
@vlad1777d 

``.. PK sensorID``

You can use more than one field in which case it will concatenate their string representation.

**Comment by vlad1777d** [comment]
@stheppi, thank you very much. Seems, that is what I need.

**Comment by andrewstevenson** [comment]
@vlad1777d Closing this issue, reopen if you still have an issue.
