### ISSUE TITLE
Cassandra Source documentation refers to Cassandra Sink

### ISSUE THREAD

**Issue by CodeSmell** [Landoop/stream-reactor#360]
The documentation for cassandra source refers to cassandra sink
The location: http://lenses.stream/connectors/source/cassandra.html

Specifically [Topic Routing](http://lenses.stream/connectors/source/cassandra.html#topic-routing)
and [Error Policies](http://lenses.stream/connectors/source/cassandra.html#error-polices)

Possibly all sections below that are also referring to the Sink.

In addition the following notes should be added
- Cassandra source only accepts one column as the PK regardless of incremental mode used
- using incremental mode of TOKEN requires Cassandra to use the Byte Ordered Partitioner or data will be missing from Kafka topic

**Comment by CodeSmell** [comment]
also looks like connect.cassandra.consistency.level is not listed as a property

**Comment by andrewstevenson** [comment]
@CodeSmell Thanks, I'm working on the docs so I'll take care of this

**Comment by andrewstevenson** [comment]
@CodeSmell Done.
