### ISSUE TITLE
issue with kafka-connect-mqtt while connecting with MQTT broker using username and password

### ISSUE THREAD

**Issue by tamilhce** [Landoop/stream-reactor#374]
The kafka-connect-mqtt(installed using the jar:afka-connect-mqtt-1.0.0-1.0.0-all.jar) works fine with anonymous connection(without user-name&password).
While connecting with MQTT broker with user-name & password authentication, In broker trace log it clearly shows that kafka-connect-mqtt couldn't pass the configured user-name & password.
I have verified with MQTT client manually, there is no issue with broker and the issue is from kafka-c
onnect-mqtt. Attached the logs for your reference.

[mqtt-source_debugging.txt](https://github.com/Landoop/stream-reactor/files/1655857/mqtt-source_debugging.txt)

**Comment by andrewstevenson** [comment]
@tamilhce thanks. We'll take a look

**Comment by caiooliveiraeti** [comment]
@tamilhce How broker you are using? I will fix this.

**Comment by Antwnis** [comment]
@tamilhce this was now fixed via #376 - if you build from master the connector you should be good to go

**Comment by tamilhce** [comment]
Thanks for the quick fix, Sure I will check and keep you guys posted.
Thank you once again
