### ISSUE TITLE
Support a vanilia Kafka Connect build

### ISSUE THREAD

**Issue by andrewstevenson** [Landoop/stream-reactor#386]
Support a vanilia Kafka Connect build

**Comment by justinsoong** [comment]
@andrewstevenson i'm actually using the MongoDB and now the ES connectors on Vanilla Connect in fact on 1.0.1 rc1 they seem to be ok, was there any breaking differences to take note?

**Comment by andmarios** [comment]
Yes indeed, our builds should be ok with vanilla kafka because we include all dependencies needed to handle avro.

**Comment by andrewstevenson** [comment]
@andmarios can we close this?

**Comment by andmarios** [comment]
Yes. In my tests the connectors work with a vanilla Kafka.
We should add it to the integration tests to make sure this is the case as well for future releases.
