### ISSUE TITLE
Class not found when running from an extended Docker image

### ISSUE THREAD

**Issue by pedromss** [Landoop/stream-reactor#408]
# Overview
I'm modyfing the `kafka-connect-jms` module and to that end I ran the `fatJar` task to obtain a runnable jar. I extended the [kafka-connect-jms](https://hub.docker.com/r/datamountaineer/kafka-connect-jms/) to this:
```docker
FROM datamountaineer/kafka-connect-jms:1.0.0

RUN mkdir /etc/config
RUN mkdir /etc/config/local

COPY templates/local /etc/config/local

COPY kafka-connect-jms-1.0.0-1.0.0-all.jar /etc/landoop/jars/kafka-connect-jms-1.0.0-1.0.0-all.jar
COPY entry-point.sh /etc/landoop/bin/entry-point.sh
CMD ["dumb-init", "/etc/landoop/bin/entry-point.sh"]
```

I also modified the `entry-point.sh` to replace the configuration in the image with mine: `templates/local/myconfig.template`

All I did to see if this docker extension worked was to print something in the flow of the JMS connector, example:

```scala
println("hello")
```
### What was the expected behaviour?
To see something else printed and assure that my changing of the docker image didn't broke anything

### What was observed?
When I did start the connector from the image I got a `ClassNotFoundException` for this class: `org.apache.activemq.jndi.ActiveMQInitialContextFactory`

### What version of the Stream Rector are you reporting this issue for?

None. I'm just using the JMS connector

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?

Running Confluent Kafka 3.3.0 for the `kafka-connect-jms:1.0.0` docker image. [This one](https://hub.docker.com/r/datamountaineer/kafka-connect-jms/)

### Have you consulted our [FAQs](http://docs.datamountaineer.com/en/latest/faq.html) page first?
Yes and I have a very similar configuration to yours. Namely this [here](https://lenses.stream/connectors/source/jms.html#starting-the-connector-distributed)

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
Using [this ActiveMQ](https://hub.docker.com/r/webcenter/activemq/) image with `latest`.

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
Don't know, didn't do anything here.

### What is your connector properties configuration (my-connector.properties)?
```text
name=sample-name
connect.jms.url=tcp://activemq:61616
connect.jms.topics=<my-activemq-topic>
connect.jms.kcql=INSERT INTO `<my-topic>` SELECT * FROM `<my-activemq-topic>` WITHTYPE TOPIC WITHJMSSELECTOR=`<my-selector>`
tasks.max=1
connector.class=com.datamountaineer.streamreactor.connect.jms.source.JMSSourceConnector
connect.jms.initial.context.factory=org.apache.activemq.jndi.ActiveMQInitialContextFactory
connect.jms.connection.factory=ConnectionFactory
```

# My solution and the whole reason to open this issue

This line [here](https://github.com/Landoop/stream-reactor/blob/master/kafka-connect-jms/build.gradle#L27) has a `testCompile` dependency on `org.apache.activemq:activemq-all`.

I thought it should be a `compile` dependency since I am compiling the JMS connector and I want to connect to ActiveMQ **and** in my configuration I am stating:

```text
connect.jms.initial.context.factory=org.apache.activemq.jndi.ActiveMQInitialContextFactory
```

So it made sense to me to change it to `compile`, so I did and it all worked out.

Is this a bug or am I configuring the connector in a wrong way? Since I could be using other JMS compliant system I'd like to think that that line should remain `testCompile` and that there is another solution to this.

**Comment by andrewstevenson** [comment]
we no longer include the active mq dependencies in the fatJar so we probably need to add that to the docker

**Comment by pedromss** [comment]
Would I be able to do that with the `cp` flag? Which file would I have to alter in the docker image?

**Comment by andrewstevenson** [comment]
@pedromss You would need to extend the docker and add the client libs for your jms provider to the plugins.dir folder

I'm closing as it's not an issue on the connector
