### ISSUE TITLE
Add SSL to mongo

### ISSUE THREAD

**Issue by andrewstevenson** [Landoop/stream-reactor#414]
It can be set in the URL but add config options for the trust/key store to make it easier to Kubernetes

**Comment by chrisfjones** [comment]
Is this covered here?
https://github.com/Landoop/kafka-helm-charts/blob/c4805035413338b047b531e3fb25e7563c448e5d/charts/kafka-connect-mongo-sink/templates/deployment.yaml#L262-L278

**Comment by andrewstevenson** [comment]
@chrisfjones You can set ssl via the URL and set the jvm properties http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/connecting/ssl/. I don't know why the chart has these options for the connector, they have never been implemented. If you want to use this in via Helm we'd have to update the charts to allow the user to set extra java opts and handle mounting the jks files (via secrets due to base64 encoding) @spirosoik
