### ISSUE TITLE
hbase version

### ISSUE THREAD

**Issue by Nik1990** [Landoop/stream-reactor#416]
Hi, i downloaded the connector at this page (version for kafka 1.0):

https://lenses.stream/connectors/sink/hbase.html

it explain that work with **hbase 1.20**. I need to know if it work also with **hbase 1.1.1** that i actually use.

Thanks

**Comment by Antwnis** [comment]
When you test, let us know by adding information on this ticket !

@iMajna was also looking at HBase 1.1.2 and he managed to achieve that by bringing in the correct library dependencies. More info here
https://github.com/Landoop/stream-reactor/pull/289

I think he managed to do a few tweaks to make things work with that HBase version

**Comment by iMajna** [comment]
@Nik1990 I will make this week pull request for Hbase1.1.2 - CP4/Kafka1.0.0 & and will change build conflicts in https://github.com/Landoop/stream-reactor/pull/289 so you will able to take a look. 

Hope it will work for you also! :)

**Comment by Antwnis** [comment]
@Nik1990 please build from above branch and please let us know how it works for you

**Comment by andrewstevenson** [comment]
Closing as we won't provide a connector 1.1.1
