### ISSUE TITLE
Kafka-connect-redis 

### ISSUE THREAD

**Issue by Mourish** [Landoop/stream-reactor#418]
# Kafka-connect-redis sink connector 
I have changed avro to json format , following issues raised
This is my error report 

>  ERROR Encountered error class java.util.HashMap is not valid. Expecting a Struct (com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache:62)
> java.lang.RuntimeException: class java.util.HashMap is not valid. Expecting a Struct
> 	at scala.sys.package$.error(package.scala:27)
> 	at com.datamountaineer.streamreactor.connect.schemas.ConverterUtil$class.convert(ConverterUtil.scala:163)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisWriter.convert(RedisWriter.scala:29)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$4.apply(RedisCache.scala:75)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$4.apply(RedisCache.scala:70)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
> 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
> 	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
> 	at scala.collection.SetLike$class.map(SetLike.scala:92)
> 	at scala.collection.AbstractSet.map(Set.scala:47)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RedisCache.scala:70)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RedisCache.scala:69)
> 	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
> 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
> 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1.apply$mcV$sp(RedisCache.scala:69)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1.apply(RedisCache.scala:69)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1.apply(RedisCache.scala:69)
> 	at scala.util.Try$.apply(Try.scala:192)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1.apply(RedisCache.scala:67)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1.apply(RedisCache.scala:61)
> 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache.insert(RedisCache.scala:61)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache.write(RedisCache.scala:55)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$put$2.apply(RedisSinkTask.scala:96)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$put$2.apply(RedisSinkTask.scala:96)
> 	at scala.collection.immutable.List.foreach(List.scala:392)

### Connect cluster configuration (connect-avro-distributed.properties)
```
bootstrap.servers=localhost:9092
group.id=connect-cluster
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
.......
```

### Connector properties configuration (redis-sink.properties)
```
name=redis-sink
connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
tasks.max=1
topics=redis-topic
connect.redis.host=localhost
connect.redis.port=6379
connect.redis.kcql=INSERT INTO data- SELECT * FROM redis-topic STOREAS SortedSet(score=timestamp)
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
```

Previously i done with cassandra its working good in json format. Is there any way to fix this above issue.

**Comment by Antwnis** [comment]
Can you also share the payload of a topic message ?

**Comment by Mourish** [comment]
@Antwnis Thanks for your response . This is my payload messages
{"packet_identifier":"1A","address":"001060AA36F8","power_level":"50","discoverer_address":"001050BB45E8","rssi":"50","timestamp":2445123}

**Comment by andrewstevenson** [comment]
@Mourish The redis sink only supports avro. We recommend to stick with Avro

**Comment by Mourish** [comment]
Hi  @andrewstevenson 

I have similar kind of issue with **avro**. In IOS client side, data payload can be serialized and send as **avro format** and i have received data, **the issue is timestamp (type: Long) value**, i got negative values  like as **[-4.1222767143500461e+17 or  4.1419586609927072e+17 or -8738** ]. I have no idea what I am doing wrong.
My payload exactly match like :**{"packet_identifier":"1A","address":"001060AA36F8","power_level":"50","discoverer_address":"001050BB45E8","rssi":"50","timestamp": 1543582860}**
At the same time , i have tested in java client side its working fine. Please suggest me what went wrong in IOS client side thanks...

**Comment by andrewstevenson** [comment]
@Mourish IOS? Is this related to the redis sink?

**Comment by Mourish** [comment]
@andrewstevenson In IOS , We are using Moquette MQTT broker code to publish data.

**Comment by Mourish** [comment]
@andrewstevenson In IOS , Iam using https://github.com/emqtt/CocoaMQTT to publish data. In server I have MQTT source connector, My Source connector look like :

```
name=mqtt-source-data
connector.class=com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector
tasks.max=1
connect.mqtt.username=testing
connect.mqtt.password=test123
connect.mqtt.connection.clean=true
connect.mqtt.connection.timeout=1000
connect.mqtt.kcql=INSERT INTO mqtt-data SELECT * FROM /MqttBrokerData WITHCONVERTER=`com.datamountaineer.streamreactor.connect.converters.source.AvroConverter`
connect.source.converter.avro.schemas=/MqttBrokerData=/tools/Mqtt/avRecord.avro
connect.mqtt.connection.keep.alive=1000
connect.mqtt.client.id=test123
connect.mqtt.converter.throw.on.error=true
connect.mqtt.hosts=tcp://127.0.0.1:11883
connect.mqtt.service.quality=1
kafka.topic=mqtt-data
mqtt.topic=MqttBrokerData
```
at the same time i have redis-sink connector properties, looks like:

```
name=redis-sink
connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
tasks.max=1
topics=redis-topic
connect.redis.host=localhost
connect.redis.port=6379
connect.redis.kcql=INSERT INTO data- SELECT * FROM mqtt-data STOREAS SortedSet(score=timestamp)
```
