### ISSUE TITLE
MQTT Source connector does not re-subscribe on reconnect

### ISSUE THREAD

**Issue by NiekPeeters** [Landoop/stream-reactor#419]
The MQTT Source connector uses the paho client's built-in mechanism for reconnecting when the connection to the broker is lost.

> In the event that the connection is lost, the paho client will attempt to reconnect to the server. It will initially wait 1 second before it attempts to reconnect, for every failed reconnect attempt, the delay will double until it is at 2 minutes at which point the delay will stay at 2 minutes.
> Source: https://github.com/eclipse/paho.mqtt.java/blob/v1.2.0/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttConnectOptions.java#L593

When the broker restarts and sessions are not persisted, subscriptions of the connector are lost. If sessions are persisted, the subscription **might** still be present; if the broker loses the entire state during restart then all subscriptions are lost regardless of session persistence.

**Comment by Nieknikey** [comment]
I think the connector should resubscribe after reconnecting to the broker regardless of session persistence. However, the paho client doesn't provide a callback for this reconnect event, so the connector cannot observe that behavior. To implement resubscription, the reconnecting logic should be implemented in the connector itself. I suppose [here](https://github.com/Landoop/stream-reactor/blob/1.0.0/kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala#L94).

This way, it would also be easy to toggle the reconnect behavior through configuration.

**Comment by Antwnis** [comment]
This sounds like a valid assesment. @Nieknikey feel free to pick this up and make a PR

Otherwise we'll look into it as soon as we get some free time on our hands

**Comment by NiekPeeters** [comment]
It turned out that the paho client does provide a callback to observe reconnects. I decided it would be easier to just use that callback instead to implement the reconnect logic myself.

**Comment by andrewstevenson** [comment]
@NiekPeeters great. Let us know how you're getting on. We are nearly ready for new release of Lenses. Stream reactor next.
