### ISSUE TITLE
RedisSinkConnector failed with Ladoop fast-data-dev docker

### ISSUE THREAD

**Issue by lwu08** [Landoop/stream-reactor#422]
Reproduce steps:

1. start Ladoop fast-data-dev and redis containers
`docker run -e CONNECTORS=redis  -e KAFKA_CONNECT_REST=http://localhost:8082 --rm --net=host landoop/fast-data-dev`
` docker run --rm  --name some-redis -d redis`

2. get into fast-data-dev container, use kafka-avro-console-producer to create a topic with data
`docker exec -it <container_id> bash`
`kafka-avro-console-producer --broker-list localhost:9092 --topic redistest --property value.schema='{"type":"record","name":"fxrate", "fields":[{"name":"symbol","type":"string"},{"name":"price","type":"double"}]}'`

Input : 
{ "symbol": "EURGBP" , "price": 0.8597 }
{ "symbol": "EURGBP" , "price": 0.12 }
{ "symbol": "EURUSD" , "price": 1.2 }
 
3. create RedisSinkConnector with following configuration
{
  "connector.class": "com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector",
  "connect.redis.retry.interval": "60000",
  "connect.redis.port": "6379",
  "connect.redis.kcql": "SELECT symbol,price from redistest PK symbol",
  "connect.redis.max.retries": "20",
  "topics": "redistest",
  "tasks.max": "1",
  "connect.redis.host": "localhost",
  "name": "RedisSinkConnector",
  "connect.redis.error.policy": "THROW",
  "connect.progress.enabled": "false"
}

4. get Error message:

TRACE:
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:484)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:265)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:182)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:150)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) 

Could you please suggest me how to solve this issue? Thanks!

**Comment by andmarios** [comment]
Hi @lwu08. If you indeed ran fast-data-dev with `-e CONNECTORS=jdbc`, then you enabled only the JDBC connector. In that case do something akin to `-e CONNECTORS=jdbc,redis` so you enable the redis connector as well.

Another issue with the commands you pasted, you never expose the redis port to the localhost (neither use --net=host).

Also please have a look on how we run basic integration tests for the redis connector:
https://github.com/Landoop/kafka-connectors-tests/tree/master/kafka-connect-redis

The `coyote.yml` file is just a bunch of bash commands. It first runs the docker-compose yml, then creates the connector and verifies entries were written into redis.

**Comment by lwu08** [comment]
@andmarios . Thanks very much for pointing out my missing.
try with `docker run --rm --name some-redis  --net=host -d redis` and ` docker run -e CONNECTORS=redis -e KAFKA_CONNECT_REST=http://localhost:8082 --rm --net=host landoop/fast-data-dev`, makes my testing works!
