### ISSUE TITLE
Error processing messages GenericData$Record cannot be cast to GenericRecord when using "WITH AVRO" in kcql 

### ISSUE THREAD

**Issue by saidbouras** [Landoop/stream-reactor#423]
When I put the "WITH AVRO" keywork in my KCQL query in JMSSink Connector, I have the this error : `GenericData$Record cannot be cast to GenericRecord`.

But when I remove those keywords, it works as expected. Maybe I misread the doc but I thought that with the keywork "WITH", we tell the connector what types of message are in the sink kafka topic.
Have I wrong ?

In activemq (so when I remove those keyword) I have that :  
```
JMS_BODY_FIELD:JMSText = {"firstName":"Said","lastName":"Bouras","age":28,"salary":3555.0}
JMS_HEADER_FIELD:JMSExpiration = 0
JMS_HEADER_FIELD:JMSMessageID = ID:kafkaconnect-37872-1523290474293-25:1:1:1:1
JMS_HEADER_FIELD:JMSPriority = 4
JMS_HEADER_FIELD:JMSDestination = jms-test-queue
JMS_HEADER_FIELD:JMSTimestamp = 1523291786303
JMS_HEADER_FIELD:JMSRedelivered = false
JMS_HEADER_FIELD:JMSDeliveryMode = persistent
```
In the first line, what is the type JMSText ?

Thanks everyone, best regards

**Comment by andrewstevenson** [comment]
@saidbouras The WITHTYPE determines the target JMS destination type, queue or topic. WITHFORMAT determines the data format of the payload sent to JMS. The message type in your topic can be anything. Kafka is agnostic but the converter type which Connect expects the message to be in is set on the workers.

What's the full stack trace as I'm curious where this error comes from?

**Comment by andrewstevenson** [comment]
@saidbouras I'm closing this as its, expected behaviour to write a json string representation of the kafka message
