### ISSUE TITLE
 SerializationException: deserializing Avro message for id -1 - Unknown magic byte!

### ISSUE THREAD

**Issue by Mourish** [Landoop/stream-reactor#426]
# Kafka-connect-redis sink connector
I publish a payload message from scala environment, i get following issue 

> org.apache.kafka.connect.errors.DataException: PayloadData
> 	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:96)
> 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:454)
> 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:287)
> 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
> 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
> 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
> 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
> Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!

## My Demo.scala code looks like :
       
> class KafkaProducer() {
> private val props = new Properties()
>         props.put("metadata.broker.list", "0.0.0.0:9092")
>         props.put("message.send.max.retries", "5")
>         props.put("request.required.acks", "-1")
>        props.put("client.id", UUID.randomUUID().toString())
>         props.put("serializer.class", "kafka.serializer.DefaultEncoder");
>  private val producer = new Producer[String, Array[Byte]](new ProducerConfig(props))
>         //Read avro schema file and
>         val schema: Schema = new 
 >     Parser().parse(Source.fromURL(getClass.getResource("/schema.avsc")).mkString)
>         def send(topic: String, users: List[KafkaMessage]): Unit = {
>                 val genericUser: GenericRecord = new GenericData.Record(schema)
>                 try {
>                         val queueMessages = users.map { user =>
>                                 // Create avro generic record object
>                                 //Put data in that generic record object
>                                 genericUser.put("data1", user.data1)
>                                 genericUser.put("data2", user.data2)
>                                 genericUser.put("data3", user.data3)
>                                 genericUser.put("timestamp", user.timestamp)
> 
>                                 // Serialize generic record object into byte array
>                                 val writer = new SpecificDatumWriter[GenericRecord](schema)
>                                 val out = new ByteArrayOutputStream()
>                                 val encoder: BinaryEncoder = EncoderFactory.get().binaryEncoder(out, null)
>                                 writer.write(genericUser, encoder)
>                                 encoder.flush()
>                                 out.close()
> 
>                                 val serializedBytes: Array[Byte] = out.toByteArray()
> 
>                                 new KeyedMessage[String, Array[Byte]](topic, serializedBytes)
>                         }
>                         producer.send(queueMessages: _*)
> } catch {
>                         case ex: Exception =>
>                                 println(ex.printStackTrace().toString)
>                                 ex.printStackTrace()
>                 }
}

### Connector properties configuration (redis-sink.properties)
name=redis-sink
connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
tasks.max=1
topics=redis-topic
connect.redis.host=localhost
connect.redis.port=6379
connect.redis.kcql=INSERT INTO data- SELECT * FROM redis-topic STOREAS SortedSet(score=timestamp)

#Through avro-console-producer, i can able to publish a message...
./bin/kafka-avro-console-producer --broker-list localhost:9092 --topic PayloadData --property value.schema='{"type":"record","name":"location_data","fields":[{"name":"data1","type":"string"},{"name":"data2","type":"string"},{"name":"data3","type":"string"},{"name":"timestamp","type":"long"}]}'

Using my scala code i cannot able to publish a message. Is there any way to fix this.

**Comment by stheppi** [comment]
@Mourish,
  Your producer doesn't send avro format. If you use Confluent's schema registry they provide their Avroserializer. Same with Hortonworks schema registry. You should check the examples for producing Avro.
