### ISSUE TITLE
Primary key (PK) clause doesn't work in kafka-connect-mongodb

### ISSUE THREAD

**Issue by invadergir** [Landoop/stream-reactor#445]
### What version of the Stream Rector are you reporting this issue for?
1.0.0

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Yes 1.0.0

### Have you consulted our [FAQs](http://docs.datamountaineer.com/en/latest/faq.html) page first?
No (Dead link.)

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
Yes.  I am using mongodb v3.6.4

### Have you read the [docs](http://lenses.stream/connectors/index.html)?
Yes

### What is the expected behaviour?
Using the kcql "UPSERT INTO coll SELECT * FROM test PK zoneId" I would expect the "_id" field in mongodb to be set to the same as the zoneId field.

### What was observed?
The _id is set to a generated ObjectId.

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
See in attached zip file: connect-distributed.properties

### What is your connector properties configuration (my-connector.properties)?
See in attached zip file: connector-config.json

### Please provide full log files (redact and sensitive information)
See in attached zip file:  log-kafka-connect.txt

[mongodbsink-pkissue.zip](https://github.com/Landoop/stream-reactor/files/2031491/mongodbsink-pkissue.zip)

**Comment by stheppi** [comment]
@invadergir ,
  We have pushed a fix on master. you can take the code and build it (see readme) and deploy the connector.

**Comment by invadergir** [comment]
That fix did the trick.  Thanks so much!!!!
