### ISSUE TITLE
On JMS Sink the KCQL's withformat TEXT is using JsonMessageConverter

### ISSUE THREAD

**Issue by aattila** [Landoop/stream-reactor#464]
Hi,

As I stated in the subject, in this way I cannot get plain text (in my case xml) messages and pass towards to the JMS queue as is. 
I also wrote a TextMessageConverter and passed to the FormatType.TEXT, if you are interested please review this pull request: https://github.com/Landoop/stream-reactor/pull/463

**Comment by andrewstevenson** [comment]
Merged in #463 so closing
