### ISSUE TITLE
Kudu Sink error - class java.util.HashMap is not valid. Expecting a Struct

### ISSUE THREAD

**Issue by Viking-Bird** [Landoop/stream-reactor#465]
I encountered a headline-like exception while saving json using kudu，I also refer to https://github.com/Landoop/stream-reactor/issues/237，Whether kudu sink also does not support org.apache.kafka.connect.json.JsonConverter？My connect-avro-distributed.properties configuration is as follows:

`key.converter=org.apache.kafka.connect.json.JsonConverter

key.converter.schemas.enable=false

value.converter=org.apache.kafka.connect.json.JsonConverter

value.converter.schemas.enable=false`

**Comment by stheppi** [comment]
Kudu connector does not support json payloads at the moment. there's a task already to add that.

**Comment by Viking-Bird** [comment]
@stheppi I know,thank you.
