### ISSUE TITLE
Kudu-Sink autocreate adds unnecessary partition

### ISSUE THREAD

**Issue by rebrendler** [Landoop/stream-reactor#472]
When auto-creating a table with a `DISTRIBUTEBY` clause using the 1.1 kudu-sink, it creates a hash partition for the requested field (as expected), but it also creates an unbounded range partition for the same field.

For example, the following KCQL:
```
UPSERT INTO impala::test.foo SELECT * FROM test.bar AUTOCREATE 
           DISTRIBUTEBY foo_id INTO 5 BUCKETS
```
Results in tablets that look like this:
```
HASH (foo_id) PARTITION 5, RANGE (foo_id) PARTITION UNBOUNDED
```
This range partition is completely unnecessary, but can affect query planning and performance.

**Comment by Antwnis** [comment]
Hey @rebrendler for clarity what should the expected table look like ?

Miss the unbounded i.e.

```
 HASH (foo_id) PARTITION 5, RANGE (foo_id) PARTITION
```

Or miss the RANGE as well 
```
 HASH (foo_id) PARTITION 5, PARTITION
```

Care to make a PR or elaborate more on the expected behaviour so that the resulting table is not having any planning / optimisation / performance issue ?

**Comment by stheppi** [comment]
Also a note Landoop Connect Sql is not KSQL  :)

**Comment by rebrendler** [comment]
Issue appears to be related to the `DbHandler. getCreateTableOptions()` use of the Kudu client's CreateTableOptions class.  From the [javadoc](https://kudu.apache.org/apidocs/org/apache/kudu/client/CreateTableOptions.html#setRangePartitionColumns-java.util.List-) for `setRangePartitionColumns()`:

"Set the columns on which the table will be range-partitioned. Every column must be a part of the table's primary key. **_If not set, the table is range partitioned by the primary key columns with a single unbounded partition._** If called with an empty vector, the table will be created without range partitioning. "

PR will be forthcoming.
