### ISSUE TITLE
How can I use the Azure Sink Connector?

### ISSUE THREAD

**Issue by marcos1990** [Landoop/stream-reactor#480]
Is there any basic procedure to follow in order to set up this connector?

**Comment by andrewstevenson** [comment]
@marcos1990 Azure sink?

**Comment by andrewstevenson** [comment]
@marcos1990 Theres a documentDB sink http://lenses.stream/connectors/sink/azuredocdb.html

**Comment by DaveSlinn** [comment]
They renamed Document Db to Cosmos Db.  Is this the one I would use to push to Cosmos Db?

**Comment by stheppi** [comment]
@DaveSlinn  yes they did  but they did not change the endpoints. It uses the Microsoft drivers for talking to CosmosDb.
