### ISSUE TITLE
KafkaConnect-InfluDB sink - Crashes Due to Running Out of Memory on Windows

### ISSUE THREAD

**Issue by pjkaufman** [Landoop/stream-reactor#486]
### What version of the Stream Rector are you reporting this issue for?

I do not believe that I am running Stream Reactor.

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?

Version 1.1.0 is the version of influx sink and kafka connect I am using.

### Have you consulted our [FAQs](http://docs.datamountaineer.com/en/latest/faq.html) page first?

I have. They do not mention anything about running out of memory.

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?

I am using influx version 1.4.3.

### Have you read the [docs](http://lenses.stream/connectors/index.html)?

I have. They do not mention anything about running out of memory.

### What is the expected behaviour?

The expected behavior is that kafka connect with the influx sink will start up and not crash after 15 minutes.

### What was observed?

I `run docker-compose up -d` and after about 15 to 20 minutes kafka connect had crashed with the following message:

``` Waiting for connect's rest API at http://kafka_connect:8083
[36mkafka_connect_1    |[0m [2018-07-28 22:17:17,582] WARN could not create Vfs.Dir from url. ignoring the exception and continuing (org.reflections.Reflections)
[36mkafka_connect_1    |[0m org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/share/java/confluent-support-metrics/*]
[36mkafka_connect_1    |[0m either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
[36mkafka_connect_1    |[0m 	at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
[36mkafka_connect_1    |[0m 	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
[36mkafka_connect_1    |[0m 	at org.reflections.Reflections.scan(Reflections.java:240)
[36mkafka_connect_1    |[0m 	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader$InternalReflections.scan(DelegatingClassLoader.java:373)
[36mkafka_connect_1    |[0m 	at org.reflections.Reflections$1.run(Reflections.java:198)
[36mkafka_connect_1    |[0m 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[36mkafka_connect_1    |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mkafka_connect_1    |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[36mkafka_connect_1    |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[36mkafka_connect_1    |[0m 	at java.lang.Thread.run(Thread.java:745)
[36mkafka_connect_1    |[0m OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000d8c00000, 132120576, 0) failed; error='Cannot allocate memory' (errno=12)
[36mkafka_connect_1    |[0m #
[36mkafka_connect_1    |[0m # There is insufficient memory for the Java Runtime Environment to continue.
[36mkafka_connect_1    |[0m # Native memory allocation (mmap) failed to map 132120576 bytes for committing reserved memory.
[36mkafka_connect_1    |[0m # An error report file with more information is saved as:
[36mkafka_connect_1    |[0m # /tmp/hs_err_pid6.log
```

### What is your Connect cluster configuration (connect-avro-distributed.properties)?

```
CONNECT_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka_connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONNECT_PLUGIN_PATH: /usr/share/java
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper:ERROR,org.I0Itec.zkclient:ERROR,org.reflections:ERROR
```

### What is your connector properties configuration (my-connector.properties)?

```
      CONNECTOR_NAME: "InfluxSink"
      CONNECTOR_CONNECTOR_CLASS: "com.datamountaineer.streamreactor.connect.influx.InfluxSinkConnector"
      CONNECTOR_TASKS_MAX: 1
      CONNECTOR_CONNECT_INFLUX_URL: "http://influx_db:8086"
      CONNECTOR_CONNECT_INFLUX_DB: "doppler"
      CONNECTOR_CONNECT_INFLUX_RETENTION_POLICY: "sixMonths"
      CONNECTOR_CONNECT_INFLUX_USERNAME=username
      CONNECTOR_CONNECT_INFLUX_PASSWORD=password
      CONNECTOR_TOPICS=influx-topic
      CONNECTOR_CONNECT_INFLUX_KCQL= KCQLQuery
```

### Please provide full log files (redact and sensitive information)

logs: 
[logs.txt](https://github.com/Landoop/stream-reactor/files/2238418/logs.txt)

/tmp/hs_err_pid6.log:
[hs_err_pid6.log](https://github.com/Landoop/stream-reactor/files/2238419/hs_err_pid6.log)

Java version:

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by pjkaufman** [comment]
I am allocating the default values to the docker toolbox. The issue is that I cannot just go into the GUI that docker has like I did on the Mac I was using. 
The memory being allocated for the vm is 1024MB. 
I tried modifying this value via the The virtual box vm instance, but the vm lost its responsiveness to docker. Is there a way to change the memory allocation in another way?

**Comment by Antwnis** [comment]
You'd have to look into the docker documentation for the Operating System you are using @pjkaufman to figure out - how to provide additional memory

**Comment by pjkaufman** [comment]
I used the process detailed at https://serverfault.com/questions/365423/how-to-run-vboxmanage-exe to increase my memory size for the default machine container for docker.

This has kept kafka_connect from crashing/
