### ISSUE TITLE
Mqtt Sink set dynamic topic

### ISSUE THREAD

**Issue by tfreiling-livongo** [Landoop/stream-reactor#491]
Is there a way to configure a mqtt-sink connector to publish to a dynamic mqtt topic that is set by a field? 
Example: 
I have the kafka topic 'mqtt-sink5' with messages like:
{"payload":31,"simID":"123456789"}
I want the connector to publish mqtt messages to the topic 'simID/123456789'

mqtt-sink.properties contains:
> name=mqtt-sink
> connector.class=com.datamountaineer.streamreactor.connect.mqtt.sink.MqttSinkConnector
> tasks.max=1
> topics=mqtt-sink5
> connect.mqtt.clean=true
> connect.mqtt.timeout=1000
> connect.mqtt.keep.alive=1000
> connect.mqtt.client.id=dm_source_id,
> connect.mqtt.hosts=tcp://localhost:1883
> connect.mqtt.service.quality=1
> connect.mqtt.kcql=INSERT INTO simID/$mqtt-sink5.simID SELECT payload,simID FROM mqtt-sink5
> connect.progress.enabled=true

**Comment by stheppi** [comment]
@tfreiling-livongo  this functionality is  not  supported at the moment. do you fancy making a PR?

**Comment by orbiran88** [comment]
Hi all, I done a quick and dirty fix for that just for my implementation.. 

You can replace the `case`  in `MqttWriter.scala` and add the relevant imports

```
import org.json4s.native.JsonMethods._
import org.json4s.DefaultFormats
```
```
   case (t, json) => {
		msg.setPayload(json.getBytes)
		val mqtttopic = (parse(json) \ "mqttTopic").extractOrElse[String]("None")
		if (mqtttopic != "None") {
		  client.publish(mqtttopic, msg)
		} else {
		  client.publish(t, msg)
		}
	  }
```

What I done is that if the payload(json..) contains the element "mqttTopic" the writer will take his value and use it as the mqtt topic for publish, that's all.

This is great for now but I will wait for a pro fix for that...

**Comment by orbiran88** [comment]
@tfreiling-livongo @stheppi 
I will make PR for that tomorrow... 
I add two new configs:
`connect.mqtt.key.as.topic` - `true\false` - Take the Kafka message key as the MQTT topic name.
`connect.mqtt.field.as.topic` - `json element name` - Take the element value from Json that came from the Kafka message payload as MQTT topic name.

If both not implemented so the MQTT topic will be taken from the KCSL statement.

**Comment by stheppi** [comment]
Hi @orbiran88,
  KCQL supports `WITHTARGET f1.f2`.
Therefore you can write 

```Insert into dummy
Select * From source
WITHTARGET _key.a````

Or 
```Insert into dummy
Select * From source
WITHTARGET a.b.c````

**Comment by orbiran88** [comment]
@stheppi Hi, thanks for that, I tested my configs with the `WITHTARGET` but its seems that the logic you mentioned not happanes, I debugged that and I can see the the dynamicTarget key contains my field name but the mqtt target not changed with the value from that field.. 
More than that, I thinks that we need to support taking the Kafka message key value as a possible target..

**Comment by stheppi** [comment]
I mentioned the Sql like syntax supports setting a dynamic target. However i didn't say the dynamic target is supported 😀. That is something to code. 

It's not much to do it. In the task when it builds the kcqlcache instance it needs to consider `getdynamictarget` before `getTarget`.  Would you like to do a PR for it?

**Comment by orbiran88** [comment]
Cool :) so yes I will make some time to handle it and make a PR.. 🥇 
I will remove to 2 configs and use the `WITHTARGET` to set if you want to use the message key `WITHTARGET $key` or a field from the payload `WITHTARGET FieldA`.

**Comment by orbiran88** [comment]
@stheppi Finished to code the logic and it's much better then what I done before.. 
I will push it soon for review.. 

#### Use message key:
```
"connect.mqtt.kcql": "INSERT INTO _key SELECT * FROM kafka.topic.name"
```

#### Use field from json:
```
"connect.mqtt.kcql": "INSERT INTO `$field` SELECT * FROM control.boxes.test WITHTARGET = field"
```
