### ISSUE TITLE
Why not publish these connectors to docker hub?

### ISSUE THREAD

**Issue by sailxjx** [Landoop/stream-reactor#493]
I can not find this repo in https://hub.docker.com/u/landoop, can anyone publish this repo to docker hub in the official group?

**Comment by andrewstevenson** [comment]
@sailxjx try this https://github.com/Landoop/dockers, they are published under DataMountaineer, they will be moved Landoop soon.

**Comment by sailxjx** [comment]
@andrewstevenson Thanks
