### ISSUE TITLE
Allow Redis sink connector to set custom delimiter in composite PK

### ISSUE THREAD

**Issue by Kvitral** [Landoop/stream-reactor#499]
Hi,
I`ve noticed that delimiter in composite PK is hardcoded:
https://github.com/Landoop/stream-reactor/blob/1e0f753764f039e9c3e7226e105a10c9ffb3fe76/kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisFieldsKeyBuilder.scala#L58

But generic KCQL syntax allow to include custom key delimiter via KEYDELIM option.
If I take example from your [docs](https://lenses.stream/connectors/sink/redis.html#test-records) :
Kafka messsage:
`
{"firstName": "John", "lastName": "Smith", "age":30, "salary": 4830}
`
KCQL :
`
INSERT INTO px- SELECT * from my_topic PK firstName,lastName
`
key in Redis :
` "px-John.Smith"`
(BTW it will be great if you include this case in your doc page, coz example docs don`t provide kcql example and it was not so intuitive for me)

But how  can I achieve smth like this:
` "px-John-Smith"`

Maybe custom delimiter might be provided via KEYDELIM option :
Kafka messsage:
`
{"firstName": "John", "lastName": "Smith", "age":30, "salary": 4830}
`
KCQL :
`
INSERT INTO px- SELECT * from my_topic PK firstName,lastName KEYDELIM -
`
key in Redis:
` "px-John-Smith"`

Updated: proper naming for KCQL

**Comment by andrewstevenson** [comment]
@Kvitral Its KCQL BTW not KSQL. I'll have a fix for you tomorrow.

**Comment by Kvitral** [comment]
Thank you for your reply.
Oh, shame on me, I`ll fix my inital comment for proper naming.
