### ISSUE TITLE
[JMS Sink Connector] URI configuration not interpreted : close timeout

### ISSUE THREAD

**Issue by saidbouras** [Landoop/stream-reactor#501]
Hi everyone !

I'm facing an issue on the JMS Sink connector version 1.0.0, I am tempting to set a timeout when the sink JMS broker isn't responding.
When I looked in the doc, I set the `connect.jms.error.policy`  to `RETRY` and `connect.jms.retry.interval` to `60000` but it's not working. When I looked deep dive into the code, I understood that this config is used by the connect task context to provide a timeout, but this is not working in my case, I stopped the activemq broker and after 25 sec the connector failed with the error below : 
```
"org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: javax.jms.IllegalStateException: [BRM.10.1205] JMS: Session is closed.\n\tat com.webmethods.jms.impl.WmSessionImpl.checkState(WmSessionImpl.java:1646)\n\tat com.webmethods.jms.impl.WmSessionImpl.rollback(WmSessionImpl.java:446)\n\tat com.datamountaineer.streamreactor.connect.jms.sink.writer.JMSWriter.write(JMSWriter.scala:66)\n\tat com.datamountaineer.streamreactor.connect.jms.sink.JMSSinkTask$$anonfun$put$1.apply(JMSSinkTask.scala:69)\n\tat com.datamountaineer.streamreactor.connect.jms.sink.JMSSinkTask$$anonfun$put$1.apply(JMSSinkTask.scala:69)\n\tat scala.Option.foreach(Option.scala:257)\n\tat com.datamountaineer.streamreactor.connect.jms.sink.JMSSinkTask.put(JMSSinkTask.scala:69)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)\n\t... 10 more\n"
```
I don't know very much activemq configs, so I looked into the documentations and it seems that we can give config to the connection through the URI so I set the config `connect.jms.url` to   `"tcp://activemq:61616?jms.closeTimeout=0"` to provide an infinite timeout when the session is closed although it doesn't work either.

It seems to me that maybe those JMS configs are overrided and that we can't provide configurations through that way ?

Below my jms sink connector configuration : 
```
{
  "name": "sink-jms",
  "config": {
    "connector.class": "com.datamountaineer.streamreactor.connect.jms.sink.JMSSinkConnector",
    "tasks.max": 1,
    "topics": "private-jms-v1",
    "connect.jms.url": "tcp://activemq:61616?jms.closeTimeout=0",
    "connect.jms.initial.context.factory": "org.apache.activemq.jndi.ActiveMQInitialContextFactory",
    "connect.jms.connection.factory": "ConnectionFactory",
    "connect.jms.queues": "jms-test-queue",
    "connect.jms.kcql": "INSERT INTO jms-test-queue SELECT * FROM private-jms-v1 WITHTYPE QUEUE",
    "key.converter" : "org.apache.kafka.connect.json.JsonConverter",
    "key.converter.schemas.enable": false,
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": false,
    "connect.jms.error.policy": "RETRY",
    "connect.progress.enabled": true,
    "connect.jms.retry.interval": 60000
  }
}
``` 

Also the JMS Sink connector documentation tells that on the `connect.jms.max.retires ` propertie is only valid when the `connect.jms.error.policy` is set to `THROW`. So it's not possible to define a number of retry when the policy is set to `RETRY` ? It's a bit odd, no ?

**Comment by andrewstevenson** [comment]
@saidbouras i think this is a bug. We try to rollback but the session is closed. Thats not wrapped in the error handler. If you want to contribute PRs are welcome! Otherwise it'll be a few days before we get to it.

**Comment by andrewstevenson** [comment]
@saidbouras https://github.com/Landoop/stream-reactor/pull/502

**Comment by saidbouras** [comment]
@andrewstevenson 
I just checked your PR, thank you :-)
I was trying this morning to do the exact same thing due to your response, but I don't understand though why the fact that we don't wrapped the error handler is linked to the JMS configuration not interpreted ?

**Comment by andrewstevenson** [comment]
@saidbouras For that you need to use the `jms.extract.props`. We pass this plus the other configuration to the JMS initialContext in JMSSessionProvider. We don't explicitly handle or overwrite the props. I'm not a JMS expert so I dunno what happens to the properties set on the URL in InitialContext.

**Comment by andrewstevenson** [comment]
@saidbouras Hopefully we'll release in the next few weeks
