### ISSUE TITLE
Exception on start (connect-cassandra)

### ISSUE THREAD

**Issue by yrsh** [Landoop/stream-reactor#506]
### What version of the Stream Rector are you reporting this issue for?
kafka-connect-cassandra-1.1.0-1.1.0

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
kafka_2.11-1.1.0

After I added kafka-connect-cassandra-1.1.0-1.1.0-all.jar in libs folder - I get exception:
`Exception in thread "main" java.lang.InstantiationError: com.typesafe.scalalogging.Logger
	at com.typesafe.scalalogging.Logger$.apply(Logger.scala:42)
	at kafka.utils.Log4jControllerRegistration$.<init>(Logging.scala:25)
	at kafka.utils.Log4jControllerRegistration$.<clinit>(Logging.scala)
	at kafka.utils.Logging$class.$init$(Logging.scala:47)
	at kafka.Kafka$.<init>(Kafka.scala:32)
	at kafka.Kafka$.<clinit>(Kafka.scala)
	at kafka.Kafka.main(Kafka.scala)`

**Comment by stheppi** [comment]
Hi @yrsh.
Can you please clarify where the libs folder sits? (a connector has a specific location it should be added to and in its own folder and set `class.path` classpath isolation) are you running standalone or distributed Connect? Have you set any classpath upfront running the Connect?

**Comment by yrsh** [comment]
Hi @stheppi!
The lib folder is just 'libs' in the root of kafka i.e. 'kafka_2.11-1.1.0/libs/'. I'm running standalone connect and kafka. No, I didn't set any classpath, just added jar and run kafka.

**Comment by andrewstevenson** [comment]
@yrsh Please use the classloader `plugin.path` you can find details [here](https://docs.lenses.io/connectors/stream-reactor-install.html#id1) Please remember to remove the jar from the other location

**Comment by yrsh** [comment]
@andrewstevenson Thanks

**Comment by andrewstevenson** [comment]
@yrsh If it works please close the issue
