### ISSUE TITLE
Avro array type not supported by InfluxDB Sink connector

### ISSUE THREAD

**Issue by afausti** [Landoop/stream-reactor#516]
I am using `stream-reactor-1.1.0` influx connector with the expected version of Kafka/Confluent. I was able to write to InfluxDB all simple data types, however the connector is failing with Avro messages containing arrays:

```
Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.IllegalArgumentException: You can't select * from the Kafka Message. Field:'Elevation_Interlocks' resolves to a Schema 'ARRAY' which will end up with a type not supported by InfluxDB API.
```

I can't change the Avro schema to avoid arrays in the first place because other consumers use them. It seems that the only option is to add support to arrays in the InfluxDB Sink Connector,  i.e., extract the array elements into individual InfluxDB fields. 

Can you provide guideline on how to implement that?

**Comment by andrewstevenson** [comment]
@afausti You would need to figure out how to write and array to InfluxDB. From a quick google you would need to explode the array and write out each element. PRs very much welcome!

**Comment by afausti** [comment]
Thanks @andrewstevenson I am failing to build the influx connector from `stream-reactor-1.1.0` source. 

After checking out the branch for that version
```$ gradle compile``` 
and
```$ gradle :kafka-connect-influx:test```
both work fine, but
```$ gradle --stacktrace :kafka-connect-influx:build```
fails with
```
> Task :kafka-connect-influxdb:signArchives FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kafka-connect-influxdb:signArchives'.
> Cannot perform signing task ':kafka-connect-influxdb:signArchives' because it has no configured signatory
```
I am not familiar with that error.

**Comment by afausti** [comment]
Update on this issue:

I'm skipping file signature since I don't need to push the files to the maven central repository.

```gradle :kafka-connect-influxdb:build -x signArchives -x test```
 
Then I produced the jar file with:

```./gradlew :kafka-connect-influxdb:shadowJar -x signArchives -x test```

**Comment by afausti** [comment]
@andrewstevenson I'm managed to write a scala function that extracts the elements from the array and add them as individual fields in InfluxDB. 

My proposed solution is in https://github.com/Landoop/stream-reactor/pull/522

**Comment by andrewstevenson** [comment]
@afausti I just merged your PR, if your happy please close!
