### ISSUE TITLE
how to create the topic for Source ftp connect(SFTP)

### ISSUE THREAD

**Issue by hamsa95** [Landoop/stream-reactor#563]
Able to create the source ftp connector, but topic for that connector is not listed in ksql.
Agenda is to create topic SFTP and push the file to S3 sink connector, but sink connector excepting topic name of source connector. so created topic manually and given in below config file

my config file

`curl -XPOST -H 'Accept: application/json' -H "Content-type: application/json" -d '{
        "name": "binary-ftp34",
        "config": {
                        "tasks.max": "1",
                        "connector.class": "com.datamountaineer.streamreactor.connect.ftp.source.FtpSourceConnector",
                        "connect.ftp.address": "ftp.drivehq.com ",
                        "connect.ftp.user": "****",
                        "connect.ftp.password": "**",
                        "connect.ftp.refresh": "PT1M",
                        "connect.ftp.file.maxage": "P14D",
                        "connect.ftp.keystyle": "struct",
                        "topic":"status011",
                       "connect.ftp.monitor.update": "/sample/employees_details.csv/:status011"
}
}' 'localhost:8083/connectors'
echo "\n"`

Tried creating the topic manually using below command
`bin/kafka-topics --create  localhost:9092 --replication-factor 1 --partitions 1 --topic status_011`

so kindly  help to solve this use case

**Comment by andrewstevenson** [comment]
@hamsa95 We don't support KSQL. Is the connector loading the files into the `status011`?

**Comment by hamsa95** [comment]
@andrewstevenson 
yup using kafka-connect-ftp-1.2.1-2.1.0-all version, but file format(avro, json, CSV) specific configuration not so clear. Just tracked the files information by filesink connector using SFTP `status011` topic in the filesink connector, uploaded the file in the folder information are tracked in the sink connector
something like this
java.nio.HeapByteBuffer[pos=0 lim=110438 cap=110438]
java.nio.HeapByteBuffer[pos=0 lim=110438 cap=110438]
java.nio.HeapByteBuffer[pos=0 lim=137028 cap=137028]

**Comment by andrewstevenson** [comment]
@hamsa95 so the connector creates the topic and loads the files. The default is to dump the file contents as one message, if you want to change this behaviour you need a converter, see https://docs.lenses.io/connectors/source/ftp.html#data-converters

I'm closing this issue as the connector is doing its job. We don't use or support KSQL so we can't help you on why its not showing there.
