### ISSUE TITLE
Tibco messages support is missing on JMS connector

### ISSUE THREAD

**Issue by hectorgarzon** [Landoop/stream-reactor#564]
For JMS connector, in method getPayload of class JMSStructMessage there is no match when the message is of type com.tibco.tibjms.TibjmsObjectMessage (we are consuming from a TIBCO queue) and therefore is failing when a message is retrieved from TIBCO:
https://github.com/Landoop/stream-reactor/blob/1.1.0/kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/domain/JMSStructMessage.scala#L80

I've tried adding this line on the `match` cases and the message is read with no error:
`case o: ObjectMessage => o.getObject().asInstanceOf[Array[Byte]]`

I can do a PR to add this feature

I've tested it on v1.1.0 of the Connector as we are using Kafka 1.1.1

**Comment by andrewstevenson** [comment]
@hectorgarzon This has been merged to master, please can you check and close the ticket if all is good?
