### ISSUE TITLE
kafka-connect-ftp: The value ``SFTP`` for config param "connect.ftp.protocol" should be renamed to ``FTPS``

### ISSUE THREAD

**Issue by alexmorosmarco** [Landoop/stream-reactor#567]
### What is the expected behaviour?
If I configure ``SFTP`` option I should be able to connect to an SFTP server.
But that does not work.

### What was observed?
I have seen that the option ``SFTP`` is actually for connecting through ``FTPS`` (FTP+TLS) protocol to an FTP server. In code I have seen that in that case we are using the ``FTPSClient`` so I understand I am not wrong. I have even tested this with a server as I have described here in a comment #505 .
So I think that the value should be renamed to ``FTPS``.

### Summary
The value ``SFTP`` for config param "connect.ftp.protocol" should be renamed to ``FTPS`` if my observations are ok.

**Comment by andrewstevenson** [comment]
Added to Lenses release 3.0 docs which are coming soon
