### ISSUE TITLE
The documentation of the connector kafka-connect-ftp is not updated in https://docs.lenses.io

### ISSUE THREAD

**Issue by alexmorosmarco** [Landoop/stream-reactor#568]
### What is the expected behaviour?
Last config params should be found in the documentation ( https://docs.lenses.io/connectors/source/ftp.html )

### What was observed?
They are not present in the docu.
This has lead to think that the connector **kafka-connect-ftp** was not even supporting ``FTPS`` protocol. But in code I actually saw it was.
I was about to discard using this great connector and finally i didn't but because I went to check the code.

This would have been really important specially when checking #505 and #567 .

**Comment by andrewstevenson** [comment]
Added in Lenses docs for release 3.0 coming soon
