### ISSUE TITLE
Suggestion - Add USE TTL to Redis Sink

### ISSUE THREAD

**Issue by wowo** [Landoop/stream-reactor#569]
### What version of the Stream Rector are you reporting this issue for?
1.2.1

### What is the expected behaviour?
Run Redis command `EXPIRE ${KEY} ${TTL_VALUE}` after value has been set when TTL = ${TTL_VALUE} has been used in KCQL in cache mode.

### What was observed?
Although I use TTL = 600 in my KCQL, it's being ignored. From what I see in the code, only Cassandra supports it (https://github.com/Landoop/stream-reactor/issues/155).

**Comment by andrewstevenson** [comment]
@wowo TTL isn't supported on the Redis sink. KCQL has various different keywords but each connector implements them differently or not at all. 

It does sound like a good feature. Do you fancy submitting a PR?

**Comment by wowo** [comment]
I'd love to, but I'm not really Scala dev.

**Comment by andrewstevenson** [comment]
@wowo TTL is support for KCQLs with an insert statement. Whats your KCQL?

**Comment by wowo** [comment]
Does it work with Redis sink? Or implemented just in Casandra sink?

**Comment by andrewstevenson** [comment]
@wowo The Redis sink. It was support for all but multisorted sets.

**Comment by andrewstevenson** [comment]
@wowo I fix has been pushed for multi sorted set support

**Comment by wowo** [comment]
Can you show the commit where it was done? Can't find it

**Comment by andrewstevenson** [comment]
@wowo https://github.com/Landoop/stream-reactor/commit/9ebb2dd30e4581a5c175678a20d287188488d5bc we did a fix in KCQL.

TTL is set in the writers

**Comment by wowo** [comment]
excellent! works like a charm!
