### ISSUE TITLE
kcql on Mongodb Sink connector always insert full message into collection even with select fields

### ISSUE THREAD

**Issue by dragonemp** [Landoop/stream-reactor#582]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Rector are you reporting this issue for?
1.2
### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Yes with latest lenses box
### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
Mongo 4.0
### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes
### What is the expected behaviour?
per your document https://docs.lenses.io/2.3/connectors/sink/mongo.html, this is expected behaviro:
--  Select specific fields from the topic sample_topic and insert into the sample collection:
INSERT INTO sample SELECT field1,field2,field3 FROM sample_topic

however, let's say my kafka message looks like this:
{
"cola": "test1",
"colb": "test2",
"colc": "test3"
}
i have this in my connector config file:
connect.mongo.kcql=INSERT INTO test SELECT cola as cold, colc FROM test-analytics

I expected the collection document would look like this:
{
"cold": "test1",
"colc": "test3"
}
### What was observed?
the full document is in collection with cola renamed to cold:
{
"cold": "test1",
"colb": "test2",
"colc": "test3"
}
### What is your Connect cluster configuration (connect-avro-distributed.properties)?
none
### What is your connector properties configuration (my-connector.properties)?
connector.class=com.datamountaineer.streamreactor.connect.mongodb.sink.MongoSinkConnector
connect.mongo.json_datetime_fields=Campaign.Modified,Campaign.Created,Campaign.StartDate,Campaign.EndDate,Contract.Modified,Contract.Created,Contract.StartDate,Contract.EndDate,Contract.ApprovedDate,Entity.Timestamp
connect.mongo.connection=mongodb://analytics-mongodb.service.consul:27018
connect.mongo.kcql=INSERT INTO leads SELECT EntityId as test123, SellerId FROM data-analytics
topics=data-analytics
value.converter.schemas.enable=false
name=analyticsMongo
errors.tolerance=all
connect.mongo.db=analytics
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter=org.apache.kafka.connect.storage.StringConverter

**Comment by klesgidis** [comment]
Do you have any update here? Is this verified? It seems that I have the same problem
