### ISSUE TITLE
Docker hub documentation

### ISSUE THREAD

**Issue by mostafaghadimi** [Landoop/stream-reactor#609]
Hi @andrewstevenson,

I have reviewed all links related to `kafka-connect-mongodb`, but there is no direct guideline of how to use from the images, specifically I need to run `kafka-connect-mongodb` image. Would you please add some docker-compose.yml file to instruct the unfamiliar users with this technology? 

Thanks

**Comment by andrewstevenson** [comment]
@mostafaghadimi have you looked here? https://github.com/Landoop/stream-reactor-dockers

All the connector options need to be added as ENV vars with the prefix `CONNECTOR_`

https://docs.lenses.io/connectors/sink/mongo.html#connector-configurations
