### ISSUE TITLE
MQTT source connector cannot reuse the session with `connect.mqtt.clean=false`

### ISSUE THREAD

**Issue by leungpeng** [Landoop/stream-reactor#621]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?
Version 1.2.1

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Kafka connect 5.3.0

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
EMQX 3.2.2

### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes

### What is the expected behaviour?
MQTT source connector should reuse the session by setting `connect.mqtt.clean=false`

### What was observed?
No incoming message after the connector restarted.

### What is your connector properties configuration (my-connector.properties)?
```
connector.class=com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector
connect.mqtt.clean=false
connect.mqtt.polling.timeout=10000
connect.mqtt.timeout=30000
tasks.max=1
connect.mqtt.kcql=INSERT INTO payload SELECT * FROM mqtt/+/data/+/+;
connect.mqtt.service.quality=1
connect.progress.enabled=true
connect.mqtt.hosts=tcp://emqtt:1883
connect.mqtt.client.id=kafkaconnector
```
### Please provide full log files (redact and sensitive information)
No error log

**Comment by andrewstevenson** [comment]
@leungpeng You are setting the flag to false so state is maintained. ```	/**
	 * Sets whether the client and server should remember state across restarts and reconnects.
	 * <ul>
	 * <li>If set to false both the client and server will maintain state across
	 * restarts of the client, the server and the connection. As state is maintained:
	 * <ul>
	 * <li>Message delivery will be reliable meeting
	 * the specified QOS even if the client, server or connection are restarted.
	 * <li> The server will treat a subscription as durable.
	 * </ul>
	 * <li>If set to true the client and server will not maintain state across
	 * restarts of the client, the server or the connection. This means
	 * <ul>
	 * <li>Message delivery to the specified QOS cannot be maintained if the
	 * client, server or connection are restarted
	 * <li>The server will treat a subscription as non-durable
	 * </ul>
	 * </ul>
	 * @param cleanSession Set to True to enable cleanSession
 	 */
	public void setCleanSession(boolean cleanSession) {
		this.cleanSession = cleanSession;
	}
```
